development: &default
  adapter: postgresql
  database: fortune_rookie_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: fortune_rookie_test
